# Generated by Django 4.0.3 on 2022-04-13 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('positive_marks', models.IntegerField(default=0)),
                ('negative_marks', models.IntegerField(default=0)),
                ('options', models.ManyToManyField(related_name='option', to='assessment.option')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('isFixed', models.BooleanField(default=False)),
                ('exam_start_time', models.DateField(blank=True, null=True)),
                ('exam_end_time', models.DateField(blank=True, null=True)),
                ('questions', models.ManyToManyField(related_name='question', to='assessment.question')),
                ('student', models.ManyToManyField(related_name='student_field', to='assessment.student')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('subjective_answer', models.CharField(blank=True, max_length=3000, null=True)),
                ('answer_submitted', models.ManyToManyField(blank=True, to='assessment.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.question')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.ManyToManyField(related_name='test_field', to='assessment.test'),
        ),
    ]
