# Generated by Django 4.0.3 on 2022-04-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_option_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='question',
        ),
        migrations.AddField(
            model_name='submission',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.test'),
        ),
        migrations.AlterField(
            model_name='student',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='test_field', to='assessment.test'),
        ),
    ]
