# Generated by Django 4.0.3 on 2022-04-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_remove_submission_question_submission_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='submission',
            field=models.ManyToManyField(related_name='submission_field', to='assessment.submission'),
        ),
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('submission', models.ManyToManyField(related_name='submission_attempts_field', to='assessment.submission')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_test', to='assessment.test')),
            ],
        ),
    ]
