# Generated by Django 4.0.3 on 2022-04-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_remove_submission_name_remove_submission_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_foreign_key', to='assessment.question'),
        ),
    ]
