# Generated by Django 4.0.3 on 2022-04-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_submission_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempts',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
    ]
