# Generated by Django 4.0.3 on 2022-04-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_remove_student_email_remove_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='test_field', to='assessment.test'),
        ),
    ]
