# Generated by Django 4.0.3 on 2022-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_alter_test_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempts',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='test',
        ),
        migrations.AddField(
            model_name='attempts',
            name='test',
            field=models.ManyToManyField(related_name='submission_attempts_field', to='assessment.test'),
        ),
    ]
