# Generated by Django 4.0.3 on 2022-04-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_remove_attempts_submission_remove_attempts_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attempts',
        ),
        migrations.AddField(
            model_name='attempts',
            name='submission',
            field=models.ManyToManyField(related_name='submission_attempts_field', to='assessment.submission'),
        ),
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='test_field', to='assessment.test'),
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='test',
        ),
        migrations.AddField(
            model_name='attempts',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_test', to='assessment.test'),
        ),
    ]
