# Generated by Django 4.0.3 on 2022-04-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_remove_student_attempts_attempts_submission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='test',
            new_name='attempted_test',
        ),
        migrations.AddField(
            model_name='student',
            name='alloted_test',
            field=models.ManyToManyField(blank=True, related_name='alloted_test', to='assessment.test'),
        ),
    ]
