# Generated by Django 4.0.3 on 2022-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_rename_test_student_attempted_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='option', to='assessment.option'),
        ),
    ]
