# Generated by Django 4.0.3 on 2022-04-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_submission_is_correct_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='highest_mark',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='is_subjected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='lowest_mark',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
