# Generated by Django 4.0.3 on 2022-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0020_question_highest_mark_question_is_subjected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_subjected',
            new_name='is_subjective',
        ),
        migrations.AlterField(
            model_name='question',
            name='highest_mark',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='lowest_mark',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
