# Generated by Django 4.0.6 on 2022-07-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0023_submission_is_answered_submission_is_attempted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='exam_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='exam_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
