# Generated by Django 4.0.6 on 2022-07-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0024_alter_test_exam_end_time_alter_test_exam_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='instructions',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
