# Generated by Django 4.0.6 on 2022-07-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0025_test_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='type',
            field=models.CharField(default='Fill in the Blanks', max_length=100),
        ),
    ]
