# Generated by Django 4.0.6 on 2022-07-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0028_submission_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='Fill in Blanks', max_length=100),
        ),
    ]
