# Generated by Django 4.0.6 on 2022-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0029_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discipline',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
