# Generated by Django 4.0.6 on 2022-07-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0031_student_city_student_state_teacher_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='discipline',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='programme',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
