# Generated by Django 4.0.6 on 2022-07-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0032_test_discipline_test_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(default='Fill in the Blanks', max_length=100),
        ),
    ]
