# Generated by Django 4.0.6 on 2022-08-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0033_alter_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='state',
        ),
    ]
