# Generated by Django 4.0.6 on 2022-08-17 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0034_remove_student_city_remove_student_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempts',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='test',
            name='time_alloted',
            field=models.IntegerField(default=0),
        ),
    ]
