# Generated by Django 4.0.6 on 2022-08-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0035_attempts_start_time_test_time_alloted'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
