# Generated by Django 4.0.6 on 2022-07-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
