# Generated by Django 4.0.6 on 2022-07-17 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_extendedusermodel_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=False, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the form of +919999999999.', regex='^\\+?1?\\d{9,14}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of opt_sent')),
                ('validated', models.BooleanField(default=False, help_text='if it is true, that means user have validate opt correctly in seconds')),
            ],
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
