# Generated by Django 4.0.6 on 2022-08-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_phoneotp_extendedusermodel_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
        migrations.RemoveField(
            model_name='extendedusermodel',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='extendedusermodel',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='state_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
