# Generated by Django 4.0.6 on 2022-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_phoneotp_remove_extendedusermodel_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='profile',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='photos'),
        ),
    ]
