# Generated by Django 4.0.6 on 2022-08-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_extendedusermodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusermodel',
            name='profile',
            field=models.ImageField(blank=True, default='/media/default/images.png', max_length=254, null=True, upload_to='photos'),
        ),
    ]
